In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('../Dataset/combined_final_dataset.csv')
data.head(10)

,Title,main_category,category,date,description
0,Over 4 Million Americans Roll Up Sleeves For O...,News,U.S. NEWS,2022-09-23,health expert said early predict whether deman...
1,"American Airlines Flyer Charged, Banned For Li...",News,U.S. NEWS,2022-09-23,subdued passenger crew fled back aircraft conf...
2,23 Of The Funniest Tweets About Cats And Dogs ...,News,COMEDY,2022-09-23,dog understand could eaten
3,The Funniest Tweets From Parents This Week (Se...,News,PARENTING,2022-09-23,accidentally put toothpaste toothbrush screame...
4,Woman Who Called Cops On Black Bird-Watcher Lo...,News,U.S. NEWS,2022-09-22,amy cooper accused investment firm franklin te...
5,Cleaner Was Dead In Belk Bathroom For 4 Days B...,News,U.S. NEWS,2022-09-22,woman seen working south carolina store thursd...
6,Reporter Gets Adorable Surprise From Her Boyfr...,News,U.S. NEWS,2022-09-22,behind anchor new asked journalist michelle ro...
7,Puerto Ricans Desperate For Water After Hurric...,News,WORLD NEWS,2022-09-22,half million people remained without water ser...
8,How A New Documentary Captures The Complexity ...,News,CULTURE & ARTS,2022-09-22,mija director isabel castro combined music doc...
9,Biden At UN To Call Russian War An Affront To ...,News,WORLD NEWS,2022-09-21,white house official say crux president visit ...

In [2]:
#Finding keywords from the description column
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

# Fit and transform the 'description' column
X = vectorizer.fit_transform(data['description'])

# Find the highest frequency words in each row
max_freq_words = []
for i, description in enumerate(data['description']):
    row = X[i].toarray().flatten()  # Convert to an array and flatten it
    sorted_word_indices = row.argsort()[-5:][::-1]  # Get indices of top 5 words
    top_5_words = [list(vectorizer.vocabulary_.keys())[list(vectorizer.vocabulary_.values()).index(idx)] for idx in sorted_word_indices]
    max_freq_words.append(top_5_words)

# Add a new 'Keyword' column to the DataFrame with the 5 maximum frequency words
data['Keyword'] = max_freq_words

ValueError: np.nan is an invalid document, expected byte or unicode string.

In [ ]:
data.head()

,Title,main_category,category,date,description,Keyword
0,Over 4 Million Americans Roll Up Sleeves For O...,News,U.S. NEWS,2022-09-23,health expert said early predict whether deman...,"[booster, dos, expert, million, would]"
1,"American Airlines Flyer Charged, Banned For Li...",News,U.S. NEWS,2022-09-23,subdued passenger crew fled back aircraft conf...,"[aircraft, according, los, angeles, office]"
2,23 Of The Funniest Tweets About Cats And Dogs ...,News,COMEDY,2022-09-23,dog understand could eaten,"[eaten, dog, understand, could, zygomatic]"
3,The Funniest Tweets From Parents This Week (Se...,News,PARENTING,2022-09-23,accidentally put toothpaste toothbrush screame...,"[toothpaste, like, dipped, tabasco, sauce]"
4,Woman Who Called Cops On Black Bird-Watcher Lo...,News,U.S. NEWS,2022-09-22,amy cooper accused investment firm franklin te...,"[unfairly, park, franklin, encounter, templeton]"

In [4]:
df = pd.read_csv('../Dataset/combined_final_dataset.csv')
df.head(10)

,Title,main_category,category,date,description
0,Over 4 Million Americans Roll Up Sleeves For O...,News,U.S. NEWS,2022-09-23,health expert said early predict whether deman...
1,"American Airlines Flyer Charged, Banned For Li...",News,U.S. NEWS,2022-09-23,subdued passenger crew fled back aircraft conf...
2,23 Of The Funniest Tweets About Cats And Dogs ...,News,COMEDY,2022-09-23,dog understand could eaten
3,The Funniest Tweets From Parents This Week (Se...,News,PARENTING,2022-09-23,accidentally put toothpaste toothbrush screame...
4,Woman Who Called Cops On Black Bird-Watcher Lo...,News,U.S. NEWS,2022-09-22,amy cooper accused investment firm franklin te...
5,Cleaner Was Dead In Belk Bathroom For 4 Days B...,News,U.S. NEWS,2022-09-22,woman seen working south carolina store thursd...
6,Reporter Gets Adorable Surprise From Her Boyfr...,News,U.S. NEWS,2022-09-22,behind anchor new asked journalist michelle ro...
7,Puerto Ricans Desperate For Water After Hurric...,News,WORLD NEWS,2022-09-22,half million people remained without water ser...
8,How A New Documentary Captures The Complexity ...,News,CULTURE & ARTS,2022-09-22,mija director isabel castro combined music doc...
9,Biden At UN To Call Russian War An Affront To ...,News,WORLD NEWS,2022-09-21,white house official say crux president visit ...

In [5]:
import yake

kw_extractor = yake.KeywordExtractor()

deduplication_threshold = 0.3
deduplication_algo = 'seqm'
windowSize = 1
numOfKeywords = 5

kw_extractor = yake.KeywordExtractor(dedupLim=deduplication_threshold, dedupFunc=deduplication_algo, windowsSize=windowSize, top=numOfKeywords)

# Extract keywords from the 'description' column and store them in a new 'Keyword' column
df['Keyword'] = df['description'].apply(lambda x: [kw[0] for kw in kw_extractor.extract_keywords(x)])

df.head()

Warning! Exception: object of type 'float' has no len() generated by the following text: 'nan'
Warning! Exception: object of type 'float' has no len() generated by the following text: 'nan'
Warning! Exception: object of type 'float' has no len() generated by the following text: 'nan'
Warning! Exception: object of type 'float' has no len() generated by the following text: 'nan'
Warning! Exception: object of type 'float' has no len() generated by the following text: 'nan'
Warning! Exception: object of type 'float' has no len() generated by the following text: 'nan'
Warning! Exception: object of type 'float' has no len() generated by the following text: 'nan'

,Title,main_category,category,date,description,Keyword
0,Over 4 Million Americans Roll Up Sleeves For O...,News,U.S. NEWS,2022-09-23,health expert said early predict whether deman...,"[booster ordered fall, match million dos, heal..."
1,"American Airlines Flyer Charged, Banned For Li...",News,U.S. NEWS,2022-09-23,subdued passenger crew fled back aircraft conf...,"[subdued passenger crew, crew fled back, fled ..."
2,23 Of The Funniest Tweets About Cats And Dogs ...,News,COMEDY,2022-09-23,dog understand could eaten,"[dog understand, understand could eaten, dog, ..."
3,The Funniest Tweets From Parents This Week (Se...,News,PARENTING,2022-09-23,accidentally put toothpaste toothbrush screame...,"[accidentally put toothpaste, dipped tabasco s..."
4,Woman Who Called Cops On Black Bird-Watcher Lo...,News,U.S. NEWS,2022-09-22,amy cooper accused investment firm franklin te...,"[amy cooper accused, accused investment firm, ..."

In [6]:
#combined datasets keywords